# Generated by Django 4.2.2 on 2023-07-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NomeCliente',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
