# Generated by Django 4.2.2 on 2023-07-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0002_alter_nomecliente_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NomeCliente',
            new_name='Clientes',
        ),
    ]
