# Generated by Django 4.2.2 on 2023-08-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0002_endereco_delete_pizza_delete_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='status_conversa',
        ),
    ]
