# Generated by Django 4.2.2 on 2023-08-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0003_remove_cliente_status_conversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status_conversa',
            field=models.TextField(default='--'),
            preserve_default=False,
        ),
    ]
