# Generated by Django 4.2.2 on 2023-07-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0003_rename_nomecliente_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='status_conversa',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
