# Generated by Django 4.2.2 on 2023-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0004_clientes_status_conversa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='status_conversa',
            field=models.CharField(max_length=60),
        ),
    ]
