# Generated by Django 4.2.2 on 2023-10-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0005_cliente_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=15, unique=True)),
                ('status_conversa', models.TextField()),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='status_conversa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.IntegerField(default=0, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsappbot.endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='whatsappbot.contato'),
            preserve_default=False,
        ),
    ]
