# Generated by Django 4.2.2 on 2023-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0007_alter_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
