# Generated by Django 4.2.2 on 2023-10-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0008_alter_cliente_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
