# Generated by Django 4.2.2 on 2023-10-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0010_alter_contato_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_cnpj', models.IntegerField(unique=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='whatsappbot.contato')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsappbot.endereco')),
            ],
        ),
    ]
