# Generated by Django 4.2.2 on 2023-10-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0012_alter_endereco_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cep',
        ),
        migrations.AddField(
            model_name='contato',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsappbot.endereco'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
