# Generated by Django 4.2.2 on 2023-10-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0014_cliente_delete_contato'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Contato',
        ),
    ]
