# Generated by Django 4.2.2 on 2023-10-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0015_rename_cliente_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField()),
                ('cpf_cnpj', models.IntegerField(unique=True)),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='whatsappbot.endereco')),
            ],
        ),
    ]
