# Generated by Django 4.2.2 on 2023-10-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0016_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='whatsappbot.contato'),
        ),
    ]
