# Generated by Django 4.2.2 on 2023-10-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0017_alter_cliente_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsappbot.endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
