# Generated by Django 4.2.2 on 2023-10-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0020_alter_cliente_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
