# Generated by Django 4.2.2 on 2023-10-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0021_delete_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=25)),
                ('cpf_cnpj', models.IntegerField(unique=True)),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='whatsappbot.contato')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsappbot.endereco')),
            ],
        ),
    ]
