# Generated by Django 4.2.2 on 2023-10-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0022_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
