# Generated by Django 4.2.2 on 2023-10-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0024_cliente_delete_contato_remove_endereco_cep_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Contato',
        ),
    ]
